'use client';
import {useEffect,useMemo,useState} from 'react';
import Logo from '../components/Logo';
import {categories,demoListings,institutions} from '../lib/data';
import {countries} from '../lib/countries';
type User={name:string;email:string;country:string;institution:string};
type Listing=typeof demoListings[number];
const money=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n);
const flag=(code:string)=>code==='OTHER'?'🌍':String.fromCodePoint(...code.split('').map(c=>127397+c.charCodeAt(0)));
export default function Page(){
 const [stage,setStage]=useState<'welcome'|'join'|'app'>('welcome'); const [user,setUser]=useState<User|null>(null); const [tab,setTab]=useState('Home'); const [q,setQ]=useState(''); const [cat,setCat]=useState('All'); const [listings,setListings]=useState<Listing[]>([]); const [sell,setSell]=useState(false); const [form,setForm]=useState({name:'',email:'',password:'',country:'KE',institution:'Kisii University'}); const [newItem,setNewItem]=useState({title:'',description:'',price:'',category:'Electronics',condition:'Good',location:''});
 useEffect(()=>{const u=localStorage.getItem('cm-user'); const l=localStorage.getItem('cm-listings'); if(u)setUser(JSON.parse(u)); setListings(l?JSON.parse(l):demoListings); const t=setTimeout(()=>setStage(u?'app':'join'),3000); return()=>clearTimeout(t)},[]);
 useEffect(()=>{localStorage.setItem('cm-listings',JSON.stringify(listings))},[listings]);
 const active=listings.filter(x=>!x.sold); const filtered=useMemo(()=>active.filter(x=>(cat==='All'||x.category===cat)&&`${x.title} ${x.description} ${x.location} ${x.institution}`.toLowerCase().includes(q.toLowerCase())),[active,cat,q]);
 function join(e:React.FormEvent){e.preventDefault(); if(!form.name||!form.email||form.password.length<6)return; const u={name:form.name,email:form.email,country:form.country,institution:form.institution}; localStorage.setItem('cm-user',JSON.stringify(u));setUser(u);setStage('app');}
 function create(e:React.FormEvent){e.preventDefault(); if(!newItem.title||!Number(newItem.price))return; const item={...newItem,id:crypto.randomUUID(),price:Number(newItem.price),seller:user?.name??'Campus Seller',institution:user?.institution??'Other / International institution',image:'🛍️',sold:false,createdAt:Date.now()};setListings(x=>[item as Listing,...x]);setNewItem({title:'',description:'',price:'',category:'Electronics',condition:'Good',location:''});setSell(false);setTab('My listings')}
 function sold(id:string){setListings(x=>x.map(i=>i.id===id?{...i,sold:true}:i))}
 if(stage==='welcome')return <main className="splash"><Logo/><h1>Welcome to Campus Mall</h1><p>Your space. Your identity. Your future.</p><small>© 2026 Campus Mall</small></main>;
 if(stage==='join')return <main className="join"><section className="join-intro"><Logo/><span className="eyebrow">CAMPUS MARKETPLACE</span><h1>Join Campus Mall</h1><p>Buy, sell and discover useful things around your campus.</p><div className="benefits"><span>✓ Campus-first marketplace</span><span>✓ Country & institution identity</span><span>✓ Seller-controlled listings</span></div></section><form className="card form" onSubmit={join}><h2>Create your account</h2><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Country<select value={form.country} onChange={e=>setForm({...form,country:e.target.value})}>{countries.map(([c,n])=><option value={c} key={c}>{flag(c)} {n}</option>)}</select></label><label>University / College<select value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}>{institutions.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary">Join Campus Mall</button><small>Prototype account data stays on this device. Production authentication/database must be configured before launch.</small></form></main>;
 return <div className="app"><header><a className="brand" href="#" onClick={()=>setTab('Home')}><Logo small/><b>Campus Mall</b></a><div className="account">{flag(user?.country??'KE')} {user?.name}<button onClick={()=>{localStorage.removeItem('cm-user');setUser(null);setStage('join')}}>Log out</button></div></header><nav>{['Home','Discover','My listings','Profile'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><main className="main">
 {tab==='Home'&&<><section className="hero"><div><span className="eyebrow">YOUR CAMPUS MARKET</span><h1>Find it.<br/><em>Sell it.</em><br/>Keep it moving.</h1><p>Campus Mall brings student-to-student buying and selling into one simple space.</p><button className="primary" onClick={()=>setSell(true)}>＋ Sell an item</button></div><div className="hero-card"><Logo/><span>SHOP · SELL · CONNECT</span></div></section><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search books, electronics, fashion..."/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="heading"><div><span className="eyebrow">FRESH LISTINGS</span><h2>Available now</h2><p>{filtered.length} active listing{filtered.length===1?'':'s'}</p></div></div><Cards items={filtered} user={user} onSold={sold}/></>}
 {tab==='Discover'&&<><span className="eyebrow">DISCOVER</span><h1>Shop by category</h1><p className="lead">Explore what your campus community is offering.</p><div className="category-grid">{categories.map(x=><button key={x} onClick={()=>{setCat(x);setTab('Home')}}><strong>{x}</strong><span>{active.filter(i=>i.category===x).length} listings</span></button>)}</div></>}
 {tab==='My listings'&&<><div className="heading row"><div><span className="eyebrow">SELLER SPACE</span><h1>My listings</h1><p>Marking an item sold removes it from the active marketplace immediately.</p></div><button className="primary" onClick={()=>setSell(true)}>＋ New listing</button></div><Cards items={active.filter(x=>x.seller===user?.name)} user={user} onSold={sold}/></>}
 {tab==='Profile'&&<><span className="eyebrow">YOUR IDENTITY</span><h1>{user?.name}</h1><div className="profile"><p><b>Email</b>{user?.email}</p><p><b>Country</b>{flag(user?.country??'KE')} {countries.find(x=>x[0]===user?.country)?.[1]}</p><p><b>University / College</b>{user?.institution}</p></div><div className="notice">For the prototype, account information is stored locally in your browser. A production launch should use secure server-side authentication, encrypted secrets, a database, access controls, backups and privacy compliance.</div></>}
 </main><footer>© 2026 Campus Mall · Your space. Your identity. Your future. · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/help">Help</a></footer>
 {sell&&<div className="modal"><form className="card form" onSubmit={create}><button type="button" className="close" onClick={()=>setSell(false)}>×</button><h2>Sell an item</h2><label>Title<input required maxLength={120} value={newItem.title} onChange={e=>setNewItem({...newItem,title:e.target.value})}/></label><label>Description<textarea maxLength={2000} value={newItem.description} onChange={e=>setNewItem({...newItem,description:e.target.value})}/></label><div className="two"><label>Price (KES)<input required type="number" min="1" value={newItem.price} onChange={e=>setNewItem({...newItem,price:e.target.value})}/></label><label>Category<select value={newItem.category} onChange={e=>setNewItem({...newItem,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="two"><label>Condition<select value={newItem.condition} onChange={e=>setNewItem({...newItem,condition:e.target.value})}><option>New</option><option>Like new</option><option>Good</option><option>Used</option></select></label><label>Location<input value={newItem.location} onChange={e=>setNewItem({...newItem,location:e.target.value})}/></label></div><button className="primary">Publish listing</button></form></div>}
 </div>}
function Cards({items,user,onSold}:{items:Listing[];user:User|null;onSold:(id:string)=>void}){if(!items.length)return <div className="empty">Nothing here yet.</div>;return <div className="grid">{items.map(i=><article className="listing" key={i.id}><div className="listing-img">{i.image}</div><div className="listing-body"><span className="tag">{i.category}</span><h3>{i.title}</h3><p>{i.description||'No description provided.'}</p><strong>{money(i.price)}</strong><div className="meta"><span>{i.institution}</span><span>{i.location||'Campus'}</span></div>{i.seller===user?.name&&<button className="sold" onClick={()=>onSold(i.id)}>Mark as sold</button>}</div></article>)}</div>}
