"use client";
import { useState } from "react";
import { countries } from "@/data/countries";
import Link from "next/link";
export default function Join(){
 const [mode,setMode]=useState<"create"|"login">("create"); const [data,setData]=useState<any>({name:"",email:"",phone:"",password:"",countryCode:"KE",university:"",accountType:"STUDENT"}); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:any){e.preventDefault();setError("");setBusy(true);const endpoint=mode==="create"?"/api/auth/register":"/api/auth/login";const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const x=await r.json();setBusy(false);if(!r.ok){setError(x.error||"Something went wrong.");return}location.href="/";}
 return <div className="auth-wrap"><div className="auth-card"><h1>{mode==="create"?"Join campus mall":"Welcome back"}</h1><p className="note">Create an account as a student or outsider and select the campus you want to use.</p><div className="hero-actions"><button className={mode==="create"?"primary-btn":"secondary-btn"} onClick={()=>setMode("create")}>Create Account</button><button className={mode==="login"?"primary-btn":"secondary-btn"} onClick={()=>setMode("login")}>Log In</button></div><form className="form" onSubmit={submit}>{mode==="create"&&<><label>Name<input required value={data.name} onChange={e=>setData({...data,name:e.target.value})}/></label><label>Country<select value={data.countryCode} onChange={e=>setData({...data,countryCode:e.target.value})}>{countries.map(c=><option key={c.code} value={c.code}>{c.flag} {c.name}</option>)}</select></label><label>University / College<input required value={data.university} onChange={e=>setData({...data,university:e.target.value})}/></label><label>Account type<select value={data.accountType} onChange={e=>setData({...data,accountType:e.target.value})}><option value="STUDENT">Student</option><option value="OUTSIDER">Outsider</option></select></label><label>Phone number<input value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label></>}<label>Email<input required type="email" value={data.email} onChange={e=>setData({...data,email:e.target.value})}/></label><label>Password<input required type="password" minLength={8} value={data.password} onChange={e=>setData({...data,password:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?"Please wait...":mode==="create"?"Create account":"Log in"}</button></form><p className="note">Support: campusmallsupport@gmail.com</p><Link href="/">← Back to marketplace</Link></div></div>
}
